### ISSUE TITLE
JOSS Feedback

### ISSUE THREAD

**Issue by joshuaeh** [mongibellili/QuantizedSystemSolver.jl#20]
Re: [JOSS Review](https://github.com/openjournals/joss-reviews/issues/7434)

A few notes while reviewing the JOSS guidelines:

- Would be helpful to have a link to the documentation on the GH repo page (to the right and within the readme) (https://mongibellili.github.io/QuantizedSystemSolver.jl/dev/)
- Installation functional, but could be described better for the Julia novices
- State of the field could be clearer: contrasting what is currently done, especially within the paper: maybe an example of a stiff system and compare approaches
- RE: the v.1.01 notes: use version control so that these are not shown until it is released then just show it and note those functions in the release changelog

- **Documentation**:
  - Landing page with description (statement of need) and installation would be good
  - The examples do a good job of showing how the qwuantized approach adds vaue with the number of dots: leverage this and maybe explain the differences between approaches
  - Tutorial: would be good to have a general simple example / just show the syntax and setup of the problem before solving the first one
  - Developer Guide:
    - Implementation page is a huge plock of text and daunting
    - Implementation: Distinguish between syntax and placeholders in the example 
  - Implementation/Dependencies hide the valuable API reference information

**Comment by mongibellili** [comment]
First of all, I am grateful for your time spent to provide these comments and suggestions.
- Direction to documentation is now clearer.
- Installation is explained in a step by step approach.
- Explanation of some limitations of the classic methods is added, and a comparison via two examples is also added.
- mentioning the capabilities of the different versions is removed from the readme.

**Documentation:**
- the landing page contains the statement of need and a detailed installation steps.
- The difference between QSS and classic methods is stated, and a comparison is added in the examples.
- The syntax to setup the problem and solve it is added before the first exmple in the tutorial section.
- The different subject are split into multiple subpages for an easier navigation, and the user API is separate.
- implementation and dependencies are minimized and kept under the developer guide.

**Comment by joshuaeh** [comment]
LGTM
